version: "3.3"

services:
  db:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  php:
    build: ./php
    volumes:
      - "./src/:/var/www/html/"
    ports:
      - 8082:80
    links:
      - db